# Generated by Django 5.0 on 2024-06-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.BooleanField(
                choices=[(0, "Сотрудник"), (1, "Закзчик")],
                verbose_name="Тип пользователя",
            ),
        ),
    ]
