# Generated by Django 5.0 on 2024-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="report",
            field=models.TextField(blank=True, help_text="Заполнить по исполнению"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("I", "In progress"), ("D", "Done")],
                default="P",
                max_length=1,
            ),
        ),
    ]
